Repository mash-up-kr/muzily-web, pull requests merged in 2022-08, with the labels that each got.

#70 feat: 플레이리스트 순서변경 기능 추가 / 메인화면 개선 / 곡 추가하기
  assets/dummy.ts
  components/domains/AddSongScreen/index.tsx
  components/domains/NowPlayingCard/index.tsx
  components/domains/PlaylistCard/index.tsx
  components/domains/PlaylistScreen/MusicItemCard.tsx
  components/domains/PlaylistScreen/index.tsx
  package.json
  pages/rooms/[roomId]/index.tsx
  public/images/heart.svg
  public/images/kebab-black.svg
  public/images/kebab.svg
  public/images/play.svg
  yarn.lock
Labels: feat

#68 feat: setup recoil and react query
  api/core/index.ts
  api/index.ts
  api/member/index.ts
  consts/api/index.ts
  consts/react-query/index.ts
  hooks/api/core/index.ts
  hooks/api/index.ts
  hooks/api/useMemberQuery/index.ts
  hooks/api/usePutMemberMutation/index.ts
  pages/_app.tsx
  pages/test/react-query-recoil/index.tsx
  store/index.ts
  store/video/index.ts
Labels: feat

#72 fix(onlyMember): MemberInfo 보장하는 바운더리 컴포넌트 추가
  contexts/MemberInfo/index.tsx
  yarn.lock
Labels: fix, feat

#74 fix(cz-customizable): v6.9.1 부터 나타난 scope skip, ^v6.3.0 -> v6.9.0으로 제한
  .cz-config.js
  package.json
  yarn.lock
Labels: bug

#62 feat: 메인 인트로 UI / 로그인 UI 추가합니다
  components/domains/KakaoLoginButton/index.tsx
  pages/login/index.tsx
  pages/main/index.tsx
  pages/main/styled.tsx
  public/images/kakao_login_large_wide.png
  public/images/star.png
Labels: feat

#82 fix(create-mood): 무드 하트 이모지 추가, 이모지 이름 형식 통일
  pages/rooms/create/mood/index.tsx
  public/images/book-3d.svg
  public/images/heart-3d.svg
  public/images/mirror-3d.svg
Labels: fix

#76 썸네일 추출 기능 추가 / 방 페이지 Recoil 적용 (useRoomStore)
  assets/dummy.ts
  components/domains/AddSongScreen/index.tsx
  components/domains/NowPlayingCard/index.tsx
  components/domains/PlaylistCard/index.tsx
  components/domains/PlaylistScreen/index.tsx
  package.json
  pages/api/thumbnail.ts
  pages/play-test/index.tsx
  pages/rooms/[roomId]/index.tsx
  store/index.ts
  store/room/index.ts
  yarn.lock
Labels: feat

#80 feat(pages/rooms/[roomId]): longPress을 아이콘 버튼에 적용
  .cz-config.js
  components/domains/PlaylistCard/index.tsx
  components/domains/PlaylistModal/MusicItemCard.tsx
  components/domains/PlaylistModal/index.tsx
  components/uis/IconButton/index.tsx
  components/uis/Layout/index.tsx
  components/uis/Modal/index.tsx
  components/uis/index.ts
  pages/rooms/[roomId]/index.tsx
  store/room/index.ts
  styles/globals.css
Labels: feat

#85 방 생성하기 API 를 추가합니다.
  api/room/index.ts
  components/uis/BottomButton/index.tsx
  pages/login/index.tsx
  pages/rooms/create/index.tsx
  pages/rooms/create/mood/index.tsx
  types/rooms/index.ts
Labels: feat

#94 feat(emoji): 강약별로 크기가 다른 이모지 날리기 추가
  assets/smile.json
  pages/rooms/[roomId]/index.tsx
Labels: feat

#95 UT 요구사항 작업
  components/domains/AddSongGuideScreen/index.tsx
  components/domains/AddSongScreen/index.tsx
  components/domains/NowPlayingCard/index.tsx
  components/domains/PlaylistModal/MusicItemCard.tsx
  components/uis/Layout/index.tsx
  components/uis/Spacer/index.tsx
  pages/rooms/[roomId]/index.tsx
  public/images/circle-question.svg
  public/images/guide-image-1.png
  public/images/guide-image-2.png
  public/images/guide-image-3.png
  public/images/guide-image-4-host.png
  public/images/guide-image-4.png
  public/images/music-status-bar.svg
  store/room/index.ts
Labels: feat

#97 feat(Routing): 방 생성 후 이동 / 뒤로 가기 라우팅 코드 추가
  components/domains/KakaoLoginButton/index.tsx
  components/uis/TopBar/TopBarIconButton.tsx
  features/auth/redirected/index.ts
  pages/index.tsx
  pages/rooms/create/mood/index.tsx
Labels: feat

#99 Feat/#98 qr code flow
  components/domains/QRCodeCard/index.tsx
  components/domains/WebShareButton/index.tsx
  components/uis/QRCodeWithLogo/index.tsx
  components/uis/TopBar/TopBarIconButton.tsx
  pages/rooms/[roomId]/index.tsx
  pages/rooms/[roomId]/invite/index.tsx
  public/images/qr-code-logo.png
  public/images/qr-code-logo.svg
Labels: feat

#87 feat(Modal): 컴포넌트 고도화 (Portal, 비동기, 중첩)
  components/uis/Modal/Close.tsx
  components/uis/Modal/Open.tsx
  components/uis/Modal/Portal.tsx
  components/uis/Modal/context.ts
  components/uis/Modal/index.tsx
  pages/test/modal/index.tsx
Labels: feat

#101 feat: 무드 페이지 추가
  components/domains/ChangeMoodScreen/index.tsx
  components/domains/MoodScreen/index.tsx
  components/domains/index.ts
  pages/rooms/[roomId]/index.tsx
  pages/rooms/create/mood/index.tsx
  public/images/caret-up.svg
  public/images/music-note.svg
  public/images/plus-circle.svg
  public/images/radio-circle-checked.svg
  public/images/radio-circle.svg
  public/images/x-circle-mono.svg
  store/room/index.ts
Labels: feat

#104 feat(Toast): 커스텀 가능한 함수형 Toast 컴포넌트 추가
  components/uis/Toast/index.tsx
  components/uis/index.ts
  libs/Toast/DefaultTemplate.tsx
  libs/Toast/Manager.tsx
  libs/Toast/context.ts
  libs/Toast/helpers/index.ts
  libs/Toast/helpers/iterateCallWithDelay.ts
  libs/Toast/hooks/index.ts
  libs/Toast/hooks/useTimeout/index.ts
  libs/Toast/hooks/useTimeoutFn/index.ts
  libs/Toast/index.tsx
  pages/test/toast/index.tsx
Labels: feat

#110 Feature/#109 emoji modalize
  assets/svgs/Heart.tsx
  components/uis/Modal/Overlay.tsx
  components/uis/Modal/index.tsx
  next.config.js
  package.json
  pages/rooms/[roomId]/index.tsx
  yarn.lock
Labels: feat

#108 feat(libs/Toast): defaultOptions 추가
  components/uis/Toast/index.tsx
  libs/Toast/index.tsx
Labels: feat

#106 feat(web-socket): 웹소켓 코어 로직 구현
  consts/index.ts
  consts/web-socket/index.ts
  contexts/Socket/index.tsx
  hooks/webSocket/index.ts
  pages/_app.tsx
  pages/socket-test/index.tsx
  store/emoji/index.ts
  store/playlist/index.ts
  store/user/index.ts
  types/emoji/index.ts
  types/playlist/index.ts
  types/webSocket/index.ts
Labels: feat

#120 방 생성 API 적용 및 직접 입력 추가합니다.
  pages/rooms/create/mood/index.tsx
  types/emojis/index.ts
  types/rooms/moods/index.ts
Labels: feat

#123 feat(login): 메인 페이지 / 리다이렉션 페이지에서 방 생성한 이력 조회해서 리다이렉션하도록 적용
  pages/index.tsx
  pages/login/redirected/index.tsx
Labels: feat

#135 feat: update mood page
  pages/rooms/[roomId]/setting/index.tsx
  pages/rooms/create/index.tsx
  pages/rooms/create/mood/index.tsx
  types/rooms/moods/index.ts
Labels: feat

#137 feat: api에 mood_description 추가 및 컴포넌트에 반영
  api/room/index.ts
  api/room/invitation/index.ts
  components/domains/Emoji/Emojis.tsx
  components/domains/Emoji/index.tsx
  pages/rooms/[roomId]/index.tsx
  pages/rooms/create/mood/index.tsx
  store/room/index.ts
  types/rooms/index.ts
  types/rooms/invitations/index.ts
  types/rooms/moods/index.ts
Labels: feat

#139 feat(playlistModal): drag & drop 고도화
  components/domains/PlaylistCard/index.tsx
  components/domains/PlaylistModal/Item.tsx
  components/domains/PlaylistModal/MusicItemCard.tsx
  components/domains/PlaylistModal/Playlist.tsx
  components/domains/PlaylistModal/context.tsx
  components/domains/PlaylistModal/hooks.ts
  components/domains/PlaylistModal/index.tsx
  components/domains/index.ts
  components/uis/Image/index.tsx
  components/uis/Modal/index.tsx
  components/uis/TopBar/index.tsx
  components/uis/index.ts
  contexts/RoomSocket/index.tsx
  hooks/commons/useLocalStorage/index.ts
  hooks/domains/index.ts
  hooks/domains/useIsViewedPlaylistItemIds/index.ts
  pages/test/dragdrop/index.tsx
Labels: feat

#141 feat(WebShareButton): 클립보드 저장되었다는 토스트 메시지 띄움
  components/domains/WebShareButton/index.tsx
Labels: feat

#143 설정 페이지 대신 모달로 띄우도록 수정
  components/domains/RoomSettingScreen/index.tsx
  pages/rooms/[roomId]/index.tsx
  pages/rooms/[roomId]/setting/index.tsx
Labels: feat

#145 feat: apply song redesign UI
  components/domains/AddSongScreen/RequestAccordion.tsx
  components/domains/AddSongScreen/index.tsx
  components/uis/TopBar/TopBarIconButton.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/rooms/[roomId]/index.tsx
  pages/rooms/[roomId]/invite/index.tsx
  public/images/accept.svg
  public/images/decline.svg
  public/images/logo.svg
  public/images/star.svg
Labels: feat

#147 feat: apply open graph
  pages/_document.tsx
  pages/rooms/[roomId]/invite/index.tsx
  public/images/og-image.png
Labels: feat
